### ISSUE TITLE
Allow setting all columns to be used for sorting

### ISSUE THREAD

**Issue by timgws** [Chumper/Datatable#331]
Allow setting all columns to be used for sorting

**Comment by timgws** [comment]
as per comment in #329

**Comment by timgws** [comment]
This is done!

**Comment by carlituxman** [comment]
just updated, but in the first column no works

**Comment by timgws** [comment]
You need to make sure that you are using the develop branch. 

Also, make sure only one column is set to order all, like this:

```php
        return Datatable::collection(User::all(array('id','name')))
            ->showColumns('id', 'name')
            ->searchColumns('name')
            ->orderColumns('*')
            ->make();
```

**Comment by carlituxman** [comment]
I do a composer update, and find at source code and I see:
f (count($cols) == 1 && $cols[0] == '*')
            $cols = $this->showColumns;

I found the problem is using columns like:

->addColumn('name', function($model) {
                    return "<a href='". route('manage.data',[$model->id])
."'>$model->name</a>";
                })



2015-09-08 11:50 GMT+02:00 Tim Groeneveld <notifications@github.com>:

> You need to make sure that you are using the develop branch.
>
> Also, make sure only one column is set to order all, like this:
>
>         return Datatable::collection(User::all(array('id','name')))            ->showColumns('id', 'name')            ->searchColumns('name')            ->orderColumns('*')            ->make();
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Chumper/Datatable/issues/331#issuecomment-138498592>.
>



-- 
*Carlos Jiménez Mora*
*INFORMATIK SOLUCIONES*
Tlf: 950 42 62 68 - Serón (Almería)
@carlituxman <https://twitter.com/carlituxman> - carlos@informatik.es

*Este mensaje y sus anexos pueden contener información confidencial, por lo
que se informa de que su uso no autorizado está prohibido por la ley. Si
Vd. considera que no es el destinatario pretendido por el remitente o no
desea recibir información comercial, por favor póngalo en su conocimiento
por esta misma vía o por cualquier otro medio y elimine esta comunicación y
los anexos de su sistema, sin copiar, remitir o revelar los contenidos del
mismo a cualquier otra persona. Cualquier información, opinión, conclusión,
recomendación, etc. contenida en el presente mensaje no relacionada con la
actividad empresarial de INFORMATIK BC SOLUCIONES S.L. y/o emitida por
persona sin capacidad para ello, deberá considerarse como no proporcionada
ni aprobada por INFORMATIK BC SOLUCIONES S.L. pone los medios a su alcance
para garantizar la seguridad y ausencia de errores en la correspondencia
electrónica, pero no puede asegurar la inexistencia de virus o la no
alteración de los documentos transmitidos electrónicamente, por lo que
declina cualquier responsabilidad a este respecto.*

**Comment by timgws** [comment]
You are indeed correct. This will need a little more work then I initially expected.

I am working on some new features currently (like Datatables 1.10 support) and will have that up and running in the next couple of days/weeks.

This will be a feature that I will be adding as part of the refactor that I am doing.

**Comment by timgws** [comment]
As a sidenote, have you tried adding the `->showColumns` after the `->addColumn`s?

**Comment by carlituxman** [comment]
adding a ->showColumns before  and using setAliasMapping() it works
