### ISSUE TITLE
groupBy problem

### ISSUE THREAD

**Issue by gapessoa** [Chumper/Datatable#70]
I really appreciate your work, but i found some problems with groupBy queries.

I have this query:
DB::table('products')
                     ->join('product_acessory', 'products.id', '=', 'product_acessory.product_id')
                     ->select(
                                 'product.name',
                                 DB::raw('COUNT(product_acessory.product_id) as total_acessories')
                      )
                      ->groupBy('product.id');

The reason is to show the amount of acessories per product in datatable.

But the pagination doesn't work rightly, because the total count trigger this raw query:

select count(*) as aggregate from `products` join `product_acessory` on `products`.`id` = `product_acessory`.`product_id` group by `product`.`id`

Any idea to solve this? 

Thx!

**Comment by mufeel** [comment]
I was able to overcome this issue by adding the following to the query ->setSearchWithAlias()
This will lead to an issue in the datatables output where the count string will look like follows:

Showing 1 to 5 of 5 entries (filtered from 8 total entries)

In order to remove this, please add the following to the the view file:

"oLanguage": {
                            "sInfoFiltered" : '',
}

This is not an ideal solution, but I had to resort to this as the update provided for this doesn't seem to work.

**Comment by ding83** [comment]
Hi,

I have the same problem also. The result set and pagination does not coincide. Thanks to mufeel that solves the problem.
